### ISSUE TITLE
Issue #1: Basic Click Counter

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/ITWEB220-2503A#37]
# Issue #1: Basic Click Counter
**Topics:** Event Listeners, DOM Manipulation, Basic JavaScript

## Overview

Create a simple click counter application that demonstrates the fundamentals of event listeners. When a user clicks a button, the counter should increment and display the new value on the page.

### HTML Structure
- Create a button with the text "Click Me!"
- Include a paragraph or div to display the current count
- The counter should start at 0

### JavaScript Functionality
- Use `addEventListener` to handle button clicks
- Store the counter value in a variable declared with `let`
- Update the displayed count each time the button is clicked
- Use string concatenation (not template literals) for updating text

### Styling
- Add basic CSS to make the counter visually appealing
- Style the button to be clearly clickable
- Make the counter display prominent and easy to read

## File Structure
```
click-counter/
├── index.html
├── main.css
└── main.js
```

## Learning Goals
By completing this exercise, you will:
- Understand basic `addEventListener` syntax
- Practice updating DOM content with JavaScript
- Learn about function scope and variable access
- Get comfortable with the connection between HTML, CSS, and JavaScript

## Getting Started
1. Create the three required files in a new folder
2. Set up the basic HTML structure with proper links to CSS and JS files
3. Add the button and counter display elements
4. Implement the click handler in JavaScript
5. Style your counter in CSS

## Expected Behavior
- Page loads showing "Count: 0"
- Each button click increases the count by 1
- The display updates immediately after each click
- The counter should work indefinitely (no maximum limit needed)

---

<details>
<summary><strong>Solution</strong></summary>

### index.html
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Click Counter</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
  <script src='main.js'></script>
</head>
<body>
  <div class="container">
    <h1>Click Counter</h1>
    <p id="counterDisplay">Count: 0</p>
    <button id="clickButton">Click Me!</button>
  </div>
</body>
</html>
```

### main.css
```css
body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    margin: 0;
    padding: 20px;
}

.container {
    text-align: center;
    max-width: 400px;
    margin: 50px auto;
    background-color: white;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

h1 {
    color: #333;
    margin-bottom: 20px;
}

#counterDisplay {
    font-size: 24px;
    font-weight: bold;
    color: #2c3e50;
    margin: 20px 0;
}

#clickButton {
    background-color: #3498db;
    color: white;
    border: none;
    padding: 15px 30px;
    font-size: 16px;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s;
}

#clickButton:hover {
    background-color: #2980b9;
}
```

### main.js
```javascript
// Variable to store the current count
let count = 0;

// Function to update the counter display
function updateCounter() {
    let displayElement = document.getElementById("counterDisplay");
    displayElement.textContent = "Count: " + count;
}

// Function to handle button clicks
function handleClick() {
    count = count + 1;
    updateCounter();
}

// Add event listener when the page loads
addEventListener('DOMContentLoaded', () => {
    let button = document.getElementById("clickButton");
    button.addEventListener("click", handleClick);
});
```

</details>
