### ISSUE TITLE
Issue #2: Multiple Element Event Handling

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/ITWEB220-2503A#38]
# Issue #2: Multiple Element Event Handling
**Topics:** Multiple Event Listeners, Function Reusability, DOM Manipulation

## Overview

Build a color picker interface with multiple colored buttons that change the background color of a target area. This exercise teaches you how to handle events from multiple elements efficiently and reuse event handler functions.

### HTML Structure
- Create a target div that will change colors (like a canvas or preview area)
- Include at least 5 colored buttons (red, blue, green, yellow, purple)
- Add a "Reset" button to return to the original color
- Include a heading that displays the currently selected color name

### JavaScript Functionality
- Use `addEventListener` for all button interactions
- Create a reusable function that can handle color changes from any button
- Update both the target div's background color AND the heading text
- Use string concatenation for updating the heading text
- Store the current color in a variable declared with `let`

### Color Requirements
- Red button changes target to red background
- Blue button changes target to blue background  
- Green button changes target to green background
- Yellow button changes target to yellow background
- Purple button changes target to purple background
- Reset button changes target back to white/light gray

### Styling
- Style the color buttons to match their respective colors
- Make the target area large and clearly visible
- Add hover effects to the buttons
- Make the current color heading prominent

## File Structure
```
color-picker/
├── index.html
├── main.css
└── main.js
```

## Learning Goals
By completing this exercise, you will:
- Learn to add event listeners to multiple elements
- Practice creating reusable event handler functions
- Understand how to pass different data through similar events
- Get comfortable managing multiple interactive elements

## Getting Started
1. Create the three required files in a new folder
2. Set up the HTML with the target div and all color buttons
3. Style the buttons and target area in CSS
4. Implement the color-changing logic in JavaScript
5. Test that all buttons work and update both color and text

## Expected Behavior
- Page loads with white/gray target area and "Current Color: None" heading
- Clicking any color button immediately changes the target area background
- The heading updates to show the selected color name
- Reset button returns everything to the initial state
- All buttons should have visual feedback (hover effects)

## Bonus Challenges
- Add a click counter that shows how many times colors have been changed
- Create a "Random Color" button that picks a random color from your options
- Add sound effects or animations when colors change

---

<details>
<summary><strong>Solution</strong></summary>

### index.html
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Color Picker</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
  <script src='main.js'></script>
</head>
<body>
  <div class="container">
    <h1>Color Picker</h1>
    <h2 id="currentColor">Current Color: None</h2>
    <div id="colorTarget"></div>
    <div class="button-group">
      <button id="redButton" class="color-btn red-btn">Red</button>
      <button id="blueButton" class="color-btn blue-btn">Blue</button>
      <button id="greenButton" class="color-btn green-btn">Green</button>
      <button id="yellowButton" class="color-btn yellow-btn">Yellow</button>
      <button id="purpleButton" class="color-btn purple-btn">Purple</button>
      <button id="resetButton" class="reset-btn">Reset</button>
    </div>
  </div>
</body>
</html>
```

### main.css
```css
body {
    font-family: Arial, sans-serif;
    background-color: #f5f5f5;
    margin: 0;
    padding: 20px;
}

.container {
    text-align: center;
    max-width: 600px;
    margin: 20px auto;
    background-color: white;
    padding: 30px;
    border-radius: 15px;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
}

h1 {
    color: #333;
    margin-bottom: 10px;
}

#currentColor {
    color: #666;
    margin-bottom: 20px;
    font-weight: normal;
}

#colorTarget {
    width: 300px;
    height: 200px;
    border: 3px solid #ddd;
    border-radius: 10px;
    margin: 20px auto;
    background-color: #f9f9f9;
    transition: background-color 0.3s ease;
}

.button-group {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: 10px;
    margin-top: 20px;
}

.color-btn, .reset-btn {
    padding: 12px 20px;
    border: none;
    border-radius: 8px;
    font-size: 14px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.3s ease;
    color: white;
    text-shadow: 1px 1px 2px rgba(0,0,0,0.3);
}

.red-btn {
    background-color: #e74c3c;
}

.red-btn:hover {
    background-color: #c0392b;
}

.blue-btn {
    background-color: #3498db;
}

.blue-btn:hover {
    background-color: #2980b9;
}

.green-btn {
    background-color: #27ae60;
}

.green-btn:hover {
    background-color: #229954;
}

.yellow-btn {
    background-color: #f1c40f;
    color: #333;
    text-shadow: none;
}

.yellow-btn:hover {
    background-color: #d4ac0d;
}

.purple-btn {
    background-color: #9b59b6;
}

.purple-btn:hover {
    background-color: #8e44ad;
}

.reset-btn {
    background-color: #95a5a6;
    color: #333;
    text-shadow: none;
}

.reset-btn:hover {
    background-color: #7f8c8d;
    color: white;
}
```

### main.js
```javascript
// Variable to store current color name
let currentColor = "None";

// Function to change color and update display
function changeColor(colorName, colorValue) {
    let targetDiv = document.getElementById("colorTarget");
    let colorHeading = document.getElementById("currentColor");
    
    // Update the background color
    targetDiv.style.backgroundColor = colorValue;
    
    // Update the current color text
    currentColor = colorName;
    colorHeading.textContent = "Current Color: " + currentColor;
}

// Function to handle red button click
function handleRedClick() {
    changeColor("Red", "#e74c3c");
}

// Function to handle blue button click
function handleBlueClick() {
    changeColor("Blue", "#3498db");
}

// Function to handle green button click
function handleGreenClick() {
    changeColor("Green", "#27ae60");
}

// Function to handle yellow button click
function handleYellowClick() {
    changeColor("Yellow", "#f1c40f");
}

// Function to handle purple button click
function handlePurpleClick() {
    changeColor("Purple", "#9b59b6");
}

// Function to handle reset button click
function handleResetClick() {
    changeColor("None", "#f9f9f9");
}

// Add all event listeners when page loads
addEventListener('DOMContentLoaded', () => {
    let redButton = document.getElementById("redButton");
    let blueButton = document.getElementById("blueButton");
    let greenButton = document.getElementById("greenButton");
    let yellowButton = document.getElementById("yellowButton");
    let purpleButton = document.getElementById("purpleButton");
    let resetButton = document.getElementById("resetButton");
    
    redButton.addEventListener("click", handleRedClick);
    blueButton.addEventListener("click", handleBlueClick);
    greenButton.addEventListener("click", handleGreenClick);
    yellowButton.addEventListener("click", handleYellowClick);
    purpleButton.addEventListener("click", handlePurpleClick);
    resetButton.addEventListener("click", handleResetClick);
});
```

</details>
