### ISSUE TITLE
Issue #3: Event Listener Toggle System

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/ITWEB220-2503A#39]
# Issue #3: Event Listener Toggle System
**Topics:** Event Listener Management, Function References, Add/Remove Listeners

## Overview

Create a "notification system" where you can enable and disable event listeners dynamically. This exercise teaches the critical concept of storing function references so you can properly remove event listeners later - a common source of bugs in JavaScript applications.

### HTML Structure
- Create 3 notification buttons: "Info", "Warning", and "Error"
- Include a display area to show notification messages
- Add "Enable All Notifications" and "Disable All Notifications" control buttons
- Include individual toggle buttons for each notification type
- Add a status indicator showing which notifications are currently active

### JavaScript Functionality
- Store ALL event handler functions in variables (this is crucial for removal)
- Implement functions to add and remove event listeners for each notification button
- Create "Enable All" and "Disable All" functionality
- Track the current state of each notification type (enabled/disabled)
- Update the status indicator whenever listeners are added or removed
- Use string concatenation for all text updates

### Notification Behaviors
- **Info button**: Shows blue "Info: This is an information message"
- **Warning button**: Shows orange "Warning: This is a warning message"  
- **Error button**: Shows red "Error: This is an error message"
- When disabled, clicking buttons should do nothing
- Messages should display in the notification area

### Status Tracking
- Show "Active Notifications: Info, Warning, Error" when all are enabled
- Update the list when individual notifications are toggled
- Show "Active Notifications: None" when all are disabled

## File Structure
```
notification-system/
├── index.html
├── main.css
└── main.js
```

## Learning Goals
By completing this exercise, you will:
- Master storing function references in variables for later removal
- Understand the requirements for successful `removeEventListener` calls
- Practice managing multiple event listeners dynamically
- Learn to track and display system state
- Avoid common event listener removal mistakes

## Getting Started
1. Create the three required files in a new folder
2. Set up HTML with all notification buttons and control buttons
3. Style the different notification types and status areas
4. Implement the event handler functions and store them in variables
5. Create the enable/disable functionality
6. Add status tracking and display updates

## Expected Behavior
- Page loads with all notifications enabled and status showing "Active: Info, Warning, Error"
- Clicking notification buttons shows appropriate colored messages
- "Disable All" button removes all event listeners - clicking notification buttons does nothing
- "Enable All" button restores all event listeners - buttons work again
- Individual toggles work for specific notification types
- Status indicator always shows current state accurately

## Common Pitfalls to Avoid
- Don't create new anonymous functions when trying to remove listeners
- Don't forget to update the status display when toggling listeners
- Make sure to test that disabled buttons truly don't respond to clicks

## Bonus Challenges
- Add a message counter showing how many notifications have been triggered
- Implement a "Clear Messages" button to empty the display area
- Add keyboard shortcuts to toggle notifications (optional)

---

<details>
<summary><strong>Solution</strong></summary>

### index.html
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Notification System</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
  <script src='main.js'></script>
</head>
<body>
  <div class="container">
    <h1>Notification System</h1>
    
    <div class="status-section">
      <h3 id="statusDisplay">Active Notifications: Info, Warning, Error</h3>
    </div>
    
    <div class="notification-buttons">
      <button id="infoButton" class="notif-btn info-btn">Info</button>
      <button id="warningButton" class="notif-btn warning-btn">Warning</button>
      <button id="errorButton" class="notif-btn error-btn">Error</button>
    </div>
    
    <div class="control-section">
      <h3>Master Controls</h3>
      <button id="enableAllButton" class="control-btn enable-btn">Enable All Notifications</button>
      <button id="disableAllButton" class="control-btn disable-btn">Disable All Notifications</button>
    </div>
    
    <div class="individual-controls">
      <h3>Individual Controls</h3>
      <button id="toggleInfoButton" class="toggle-btn">Toggle Info</button>
      <button id="toggleWarningButton" class="toggle-btn">Toggle Warning</button>
      <button id="toggleErrorButton" class="toggle-btn">Toggle Error</button>
    </div>
    
    <div class="message-area">
      <h3>Messages</h3>
      <div id="messageDisplay">No messages yet...</div>
    </div>
  </div>
</body>
</html>
```

### main.css
```css
body {
    font-family: Arial, sans-serif;
    background-color: #f8f9fa;
    margin: 0;
    padding: 20px;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    background-color: white;
    padding: 30px;
    border-radius: 12px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.1);
}

h1 {
    text-align: center;
    color: #333;
    margin-bottom: 30px;
}

h3 {
    color: #555;
    margin-bottom: 15px;
}

.status-section {
    background-color: #e9ecef;
    padding: 15px;
    border-radius: 8px;
    margin-bottom: 25px;
    text-align: center;
}

#statusDisplay {
    margin: 0;
    font-weight: bold;
    color: #495057;
}

.notification-buttons {
    display: flex;
    justify-content: center;
    gap: 15px;
    margin-bottom: 30px;
}

.notif-btn {
    padding: 15px 25px;
    border: none;
    border-radius: 8px;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.3s ease;
    color: white;
}

.info-btn {
    background-color: #17a2b8;
}

.info-btn:hover {
    background-color: #138496;
}

.warning-btn {
    background-color: #ffc107;
    color: #333;
}

.warning-btn:hover {
    background-color: #e0a800;
}

.error-btn {
    background-color: #dc3545;
}

.error-btn:hover {
    background-color: #c82333;
}

.control-section, .individual-controls {
    text-align: center;
    margin-bottom: 25px;
    padding: 20px;
    background-color: #f8f9fa;
    border-radius: 8px;
}

.control-btn, .toggle-btn {
    padding: 10px 20px;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    cursor: pointer;
    margin: 5px;
    transition: all 0.3s ease;
}

.enable-btn {
    background-color: #28a745;
    color: white;
}

.enable-btn:hover {
    background-color: #218838;
}

.disable-btn {
    background-color: #6c757d;
    color: white;
}

.disable-btn:hover {
    background-color: #5a6268;
}

.toggle-btn {
    background-color: #007bff;
    color: white;
}

.toggle-btn:hover {
    background-color: #0056b3;
}

.message-area {
    background-color: #f8f9fa;
    padding: 20px;
    border-radius: 8px;
    border: 1px solid #dee2e6;
}

#messageDisplay {
    min-height: 100px;
    background-color: white;
    padding: 15px;
    border-radius: 6px;
    border: 1px solid #dee2e6;
    font-family: monospace;
    white-space: pre-wrap;
}

.message-info {
    color: #17a2b8;
    font-weight: bold;
}

.message-warning {
    color: #ffc107;
    font-weight: bold;
}

.message-error {
    color: #dc3545;
    font-weight: bold;
}
```

### main.js
```javascript
// State tracking variables
let infoEnabled = true;
let warningEnabled = true;
let errorEnabled = true;

// Store function references for event handlers
let infoHandler = () => showMessage("Info: This is an information message", "info");
let warningHandler = () => showMessage("Warning: This is a warning message", "warning");
let errorHandler = () => showMessage("Error: This is an error message", "error");

// Function to display messages
function showMessage(message, type) {
    let messageDisplay = document.getElementById("messageDisplay");
    let timestamp = new Date().toLocaleTimeString();
    let fullMessage = "[" + timestamp + "] " + message + "\n";
    
    if (messageDisplay.textContent === "No messages yet...") {
        messageDisplay.textContent = "";
    }
    
    messageDisplay.textContent = messageDisplay.textContent + fullMessage;
    messageDisplay.scrollTop = messageDisplay.scrollHeight;
}

// Function to update status display
function updateStatus() {
    let statusDisplay = document.getElementById("statusDisplay");
    let activeNotifications = [];
    
    if (infoEnabled) {
        activeNotifications.push("Info");
    }
    if (warningEnabled) {
        activeNotifications.push("Warning");
    }
    if (errorEnabled) {
        activeNotifications.push("Error");
    }
    
    if (activeNotifications.length === 0) {
        statusDisplay.textContent = "Active Notifications: None";
    } else {
        statusDisplay.textContent = "Active Notifications: " + activeNotifications.join(", ");
    }
}

// Functions to enable individual notifications
function enableInfo() {
    if (!infoEnabled) {
        let infoButton = document.getElementById("infoButton");
        infoButton.addEventListener("click", infoHandler);
        infoEnabled = true;
        updateStatus();
    }
}

function enableWarning() {
    if (!warningEnabled) {
        let warningButton = document.getElementById("warningButton");
        warningButton.addEventListener("click", warningHandler);
        warningEnabled = true;
        updateStatus();
    }
}

function enableError() {
    if (!errorEnabled) {
        let errorButton = document.getElementById("errorButton");
        errorButton.addEventListener("click", errorHandler);
        errorEnabled = true;
        updateStatus();
    }
}

// Functions to disable individual notifications
function disableInfo() {
    if (infoEnabled) {
        let infoButton = document.getElementById("infoButton");
        infoButton.removeEventListener("click", infoHandler);
        infoEnabled = false;
        updateStatus();
    }
}

function disableWarning() {
    if (warningEnabled) {
        let warningButton = document.getElementById("warningButton");
        warningButton.removeEventListener("click", warningHandler);
        warningEnabled = false;
        updateStatus();
    }
}

function disableError() {
    if (errorEnabled) {
        let errorButton = document.getElementById("errorButton");
        errorButton.removeEventListener("click", errorHandler);
        errorEnabled = false;
        updateStatus();
    }
}

// Master control functions
function enableAllNotifications() {
    enableInfo();
    enableWarning();
    enableError();
}

function disableAllNotifications() {
    disableInfo();
    disableWarning();
    disableError();
}

// Toggle functions
function toggleInfo() {
    if (infoEnabled) {
        disableInfo();
    } else {
        enableInfo();
    }
}

function toggleWarning() {
    if (warningEnabled) {
        disableWarning();
    } else {
        enableWarning();
    }
}

function toggleError() {
    if (errorEnabled) {
        disableError();
    } else {
        enableError();
    }
}

// Initialize everything when page loads
addEventListener('DOMContentLoaded', () => {
    // Add initial event listeners for notification buttons
    let infoButton = document.getElementById("infoButton");
    let warningButton = document.getElementById("warningButton");
    let errorButton = document.getElementById("errorButton");
    
    infoButton.addEventListener("click", infoHandler);
    warningButton.addEventListener("click", warningHandler);
    errorButton.addEventListener("click", errorHandler);
    
    // Add event listeners for control buttons
    let enableAllButton = document.getElementById("enableAllButton");
    let disableAllButton = document.getElementById("disableAllButton");
    
    enableAllButton.addEventListener("click", enableAllNotifications);
    disableAllButton.addEventListener("click", disableAllNotifications);
    
    // Add event listeners for toggle buttons
    let toggleInfoButton = document.getElementById("toggleInfoButton");
    let toggleWarningButton = document.getElementById("toggleWarningButton");
    let toggleErrorButton = document.getElementById("toggleErrorButton");
    
    toggleInfoButton.addEventListener("click", toggleInfo);
    toggleWarningButton.addEventListener("click", toggleWarning);
    toggleErrorButton.addEventListener("click", toggleError);
    
    // Initialize status display
    updateStatus();
});
```

</details>
