### ISSUE TITLE
Issue #4: Dynamic Event Management

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/ITWEB220-2503A#40]
# Issue #4: Dynamic Event Management
**Topics:** Dynamic Element Creation, Event Listener Lifecycle, Memory Management

## Overview

Build a "task manager" where you can dynamically add new task buttons to the page, with each button getting its own event listener. You'll also implement functionality to remove individual tasks and their associated event listeners. This exercise teaches proper event listener lifecycle management and avoiding memory leaks.

### HTML Structure
- Create an input field for entering new task names
- Include an "Add Task" button to create new task items
- Add a container area where task buttons will be dynamically added
- Include a "Clear All Tasks" button to remove everything
- Add a status area showing the current number of active tasks

### JavaScript Functionality
- Dynamically create new task buttons when "Add Task" is clicked
- Each task button should have its own unique event listener
- Store references to ALL dynamically created elements and their event handlers
- Implement individual task removal with proper event listener cleanup
- Track the total number of tasks and update the display
- Use string concatenation for all text updates
- Clear the input field after adding each task

### Task Behaviors
- **Adding Tasks**: Create a new button with the task name and a "Remove" button
- **Task Click**: Show an alert saying "Task completed: [task name]"
- **Remove Click**: Remove the task from the page and clean up its event listeners
- **Clear All**: Remove all tasks and clean up all event listeners
- **Empty Input Handling**: Don't create tasks with empty names

### Dynamic Element Structure
Each task should be a container with:
- Task button displaying the task name
- Remove button (styled differently)
- Proper event listeners for both buttons
- Unique identifiers for tracking

### Memory Management
- Store references to all created elements
- Store references to all event handler functions
- Properly remove event listeners before removing elements
- Update the task counter whenever tasks are added or removed

## File Structure
```
task-manager/
├── index.html
├── main.css
└── main.js
```

## Learning Goals
By completing this exercise, you will:
- Master dynamic element creation and event listener attachment
- Learn proper cleanup techniques to prevent memory leaks
- Practice managing collections of elements and their associated handlers
- Understand the lifecycle of dynamically created content
- Handle edge cases like empty inputs and duplicate operations

## Getting Started
1. Create the three required files in a new folder
2. Set up HTML with input field, buttons, and task container
3. Style the task items and different button types
4. Implement dynamic task creation with proper event listener attachment
5. Add removal functionality with complete cleanup
6. Test memory management by adding and removing many tasks

## Expected Behavior
- Page loads with empty task list and "Active Tasks: 0"
- Typing a task name and clicking "Add Task" creates a new task button
- Each task button shows completion alert when clicked
- Remove buttons delete individual tasks immediately
- Task counter updates accurately as tasks are added/removed
- "Clear All" removes everything and resets counter to 0
- Empty task names should not create new tasks

## Common Pitfalls to Avoid
- Don't forget to remove event listeners before removing elements
- Don't reuse the same event handler function for different tasks
- Make sure each task has unique identifiers
- Remember to update the task counter in all scenarios

## Bonus Challenges
- Add task editing functionality (double-click to edit)
- Implement task completion status (strikethrough completed tasks)
- Add drag-and-drop reordering of tasks
- Save tasks to browser storage and restore on page load (advanced)

---

<details>
<summary><strong>Solution</strong></summary>

### index.html
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Dynamic Task Manager</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
  <script src='main.js'></script>
</head>
<body>
  <div class="container">
    <h1>Dynamic Task Manager</h1>
    
    <div class="status-section">
      <h3 id="taskCounter">Active Tasks: 0</h3>
    </div>
    
    <div class="input-section">
      <input type="text" id="taskInput" placeholder="Enter a new task..." maxlength="50">
      <button id="addTaskButton" class="add-btn">Add Task</button>
      <button id="clearAllButton" class="clear-btn">Clear All Tasks</button>
    </div>
    
    <div class="tasks-container">
      <h3>Your Tasks</h3>
      <div id="tasksArea">
        <p class="empty-message">No tasks yet. Add one above!</p>
      </div>
    </div>
  </div>
</body>
</html>
```

### main.css
```css
body {
    font-family: Arial, sans-serif;
    background-color: #f4f6f9;
    margin: 0;
    padding: 20px;
}

.container {
    max-width: 700px;
    margin: 0 auto;
    background-color: white;
    padding: 30px;
    border-radius: 12px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.1);
}

h1 {
    text-align: center;
    color: #2c3e50;
    margin-bottom: 30px;
}

h3 {
    color: #34495e;
    margin-bottom: 15px;
}

.status-section {
    background-color: #ecf0f1;
    padding: 15px;
    border-radius: 8px;
    text-align: center;
    margin-bottom: 25px;
}

#taskCounter {
    margin: 0;
    font-weight: bold;
    color: #2c3e50;
}

.input-section {
    display: flex;
    gap: 10px;
    margin-bottom: 30px;
    align-items: center;
}

#taskInput {
    flex: 1;
    padding: 12px;
    border: 2px solid #bdc3c7;
    border-radius: 6px;
    font-size: 16px;
    outline: none;
    transition: border-color 0.3s;
}

#taskInput:focus {
    border-color: #3498db;
}

.add-btn {
    background-color: #27ae60;
    color: white;
    border: none;
    padding: 12px 20px;
    border-radius: 6px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s;
}

.add-btn:hover {
    background-color: #229954;
}

.clear-btn {
    background-color: #e74c3c;
    color: white;
    border: none;
    padding: 12px 20px;
    border-radius: 6px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s;
}

.clear-btn:hover {
    background-color: #c0392b;
}

.tasks-container {
    background-color: #f8f9fa;
    padding: 20px;
    border-radius: 8px;
    border: 1px solid #dee2e6;
}

#tasksArea {
    min-height: 100px;
}

.empty-message {
    text-align: center;
    color: #6c757d;
    font-style: italic;
    margin: 40px 0;
}

.task-item {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 10px;
    padding: 15px;
    background-color: white;
    border-radius: 8px;
    border: 1px solid #dee2e6;
    box-shadow: 0 2px 4px rgba(0,0,0,0.05);
}

.task-button {
    flex: 1;
    background-color: #3498db;
    color: white;
    border: none;
    padding: 10px 15px;
    border-radius: 6px;
    font-size: 14px;
    cursor: pointer;
    text-align: left;
    transition: background-color 0.3s;
}

.task-button:hover {
    background-color: #2980b9;
}

.remove-button {
    background-color: #e74c3c;
    color: white;
    border: none;
    padding: 10px 15px;
    border-radius: 6px;
    font-size: 14px;
    cursor: pointer;
    transition: background-color 0.3s;
}

.remove-button:hover {
    background-color: #c0392b;
}

.task-item:hover {
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    transition: all 0.2s;
}
```

### main.js
```javascript
// Global variables to track tasks and their handlers
let taskCount = 0;
let taskHandlers = {}; // Store event handlers by task ID
let taskElements = {}; // Store DOM elements by task ID

// Function to update the task counter display
function updateTaskCounter() {
    let counterElement = document.getElementById("taskCounter");
    counterElement.textContent = "Active Tasks: " + taskCount;
}

// Function to show/hide empty message
function updateEmptyMessage() {
    let tasksArea = document.getElementById("tasksArea");
    let emptyMessage = tasksArea.querySelector(".empty-message");
    
    if (taskCount === 0) {
        if (!emptyMessage) {
            let message = document.createElement("p");
            message.className = "empty-message";
            message.textContent = "No tasks yet. Add one above!";
            tasksArea.appendChild(message);
        }
    } else {
        if (emptyMessage) {
            emptyMessage.remove();
        }
    }
}

// Function to create a unique task ID
function generateTaskId() {
    return "task_" + Date.now() + "_" + Math.random().toString(36).substr(2, 9);
}

// Function to handle task completion
function createTaskHandler(taskName, taskId) {
    return () => {
        alert("Task completed: " + taskName);
    };
}

// Function to handle task removal
function createRemoveHandler(taskId) {
    return () => {
        removeTask(taskId);
    };
}

// Function to add a new task
function addTask() {
    let taskInput = document.getElementById("taskInput");
    let taskName = taskInput.value.trim();
    
    // Don't create empty tasks
    if (taskName === "") {
        alert("Please enter a task name!");
        return;
    }
    
    // Generate unique ID for this task
    let taskId = generateTaskId();
    
    // Create task container
    let taskItem = document.createElement("div");
    taskItem.className = "task-item";
    taskItem.id = taskId;
    
    // Create task button
    let taskButton = document.createElement("button");
    taskButton.className = "task-button";
    taskButton.textContent = taskName;
    
    // Create remove button
    let removeButton = document.createElement("button");
    removeButton.className = "remove-button";
    removeButton.textContent = "Remove";
    
    // Create event handlers and store them
    let taskHandler = createTaskHandler(taskName, taskId);
    let removeHandler = createRemoveHandler(taskId);
    
    // Store handlers for later cleanup
    taskHandlers[taskId] = {
        taskHandler: taskHandler,
        removeHandler: removeHandler
    };
    
    // Store DOM elements for later cleanup
    taskElements[taskId] = {
        taskItem: taskItem,
        taskButton: taskButton,
        removeButton: removeButton
    };
    
    // Add event listeners
    taskButton.addEventListener("click", taskHandler);
    removeButton.addEventListener("click", removeHandler);
    
    // Build the task item
    taskItem.appendChild(taskButton);
    taskItem.appendChild(removeButton);
    
    // Add to the tasks area
    let tasksArea = document.getElementById("tasksArea");
    tasksArea.appendChild(taskItem);
    
    // Update counters and displays
    taskCount = taskCount + 1;
    updateTaskCounter();
    updateEmptyMessage();
    
    // Clear the input field
    taskInput.value = "";
    taskInput.focus();
}

// Function to remove a specific task
function removeTask(taskId) {
    // Get stored elements and handlers
    let elements = taskElements[taskId];
    let handlers = taskHandlers[taskId];
    
    if (elements && handlers) {
        // Remove event listeners first
        elements.taskButton.removeEventListener("click", handlers.taskHandler);
        elements.removeButton.removeEventListener("click", handlers.removeHandler);
        
        // Remove the DOM element
        elements.taskItem.remove();
        
        // Clean up stored references
        delete taskElements[taskId];
        delete taskHandlers[taskId];
        
        // Update counters and displays
        taskCount = taskCount - 1;
        updateTaskCounter();
        updateEmptyMessage();
    }
}

// Function to clear all tasks
function clearAllTasks() {
    // Get all task IDs
    let taskIds = Object.keys(taskElements);
    
    // Remove each task properly
    for (let i = 0; i < taskIds.length; i = i + 1) {
        removeTask(taskIds[i]);
    }
}

// Function to handle Enter key in input field
function handleInputKeyPress(event) {
    if (event.key === "Enter") {
        addTask();
    }
}

// Initialize everything when page loads
addEventListener('DOMContentLoaded', () => {
    // Get control elements
    let addTaskButton = document.getElementById("addTaskButton");
    let clearAllButton = document.getElementById("clearAllButton");
    let taskInput = document.getElementById("taskInput");
    
    // Add event listeners for controls
    addTaskButton.addEventListener("click", addTask);
    clearAllButton.addEventListener("click", clearAllTasks);
    taskInput.addEventListener("keypress", handleInputKeyPress);
    
    // Initialize displays
    updateTaskCounter();
    updateEmptyMessage();
    
    // Focus on input field
    taskInput.focus();
});
```

</details>
